---
- name: Install CategoryCompare Web Dependencies
  hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    # NOTE: Uncomment these lines in order to add swap space to the target machine. This can be needed
    #       when installing packages on, IE: EC2 instances, due to their low memory specs. This step
    #       is commented out because, after the swap space has been added once, it shouldn't be added
    #       again in the future.
    # - name: Add swap space (1/5) - create swap file
    #   command: fallocate -l 512M /mnt/swapfile.swap creates=/mnt/swapfile.swap
    # - name: Register whether or not the swap file actually exists in Ansible
    #   stat: path=/mnt/swapfile.swap
    #   register: swapfile
    # - name: Add swap space (2/5) - format swap file
    #   command: mkswap /mnt/swapfile.swap
    #   when: swapfile.stat.exists
    # - name: Add swap space (3/5) - set swap file permissions
    #   file: path=/mnt/swapfile.swap owner=root group=root mode=0600
    #   when: swapfile.stat.exists
    # - name: Add swap space (4/5) - have the system consider the swap file to be swap
    #   command: swapon /mnt/swapfile.swap
    #   when: swapfile.stat.exists
    # - name: Add swap space (5/5) - write swap entry in fstab
    #   mount: name=noe src=/mnt/swapfile.swap fstype=swap opts=sw passno=0 dump=0 state=present
    #   when: swapfile.stat.exists

    - name: Add CRAN repository to APT repository list
      apt_repository: repo='deb http://cran.rstudio.com/bin/linux/ubuntu trusty/' state=present

    - name: Install R
      apt: pkg=r-base state=latest
    - name: Install Ruby
      apt: pkg=ruby-full state=latest
    - name: Install Rserve
      apt: pkg=r-cran-rserve state=latest
    - name: Install SQLite3 prerequisite packages
      # The SQLite3 Ruby gem needs this package installed in order to
      # work. See: https://stackoverflow.com/questions/3458602/sqlite3-ruby-install-error-on-ubuntu
      apt: pkg=libsqlite3-dev state=latest
    - name: Install Bioconductor prerequisite packages (1/2) - XML
      apt: pkg=libxml2-dev state=latest
    - name: Install Bioconductor prerequisite packages (2/2) - RCurl
      apt: pkg=libcurl4-openssl-dev
    - name: Install Ruby gems from Bundler
      become: no
      bundler: state=present gemfile=~/SourceCode/CategoryCompare-WebApp-Application/Gemfile

    # === Fix Ubuntu's broken Rserve package ===
    # Ubuntu's rserve package doesn't set symlinks properly.
    # See here for more info: https://bugs.launchpad.net/ubuntu/+source/rserve/+bug/1325325
    - name: Add missing Rserve symlinks - (1/2)
      file: src=/usr/lib/R/site-library/Rserve/libs/Rserve dest=/usr/lib/R/bin/Rserve owner=root state=link force=yes
    - name: Add missing Rserve symlinks - (2/2)
      file: src=/usr/lib/R/site-library/Rserve/libs/Rserve.dbg dest=/usr/lib/R/bin/Rserve.dbg owner=root state=link force=yes

#    - bundler: state=present gemfile=~/SourceCode/CategoryCompare-WebApp-Application/Gemfile