---
- name: Install CategoryCompare Web Dependencies
  hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install R
      apt: pkg=r-base state=latest
    - name: Install Ruby
      apt: pkg=ruby-full state=latest
    - name: Install Rserve
      apt: pkg=r-cran-rserve state=latest
    - name: Install SQLite3 prerequisite packages
      # The SQLite3 Ruby gem needs this package installed in order to
      # work. See: https://stackoverflow.com/questions/3458602/sqlite3-ruby-install-error-on-ubuntu
      apt: pkg=libsqlite3-dev state=latest
    - name: Install Ruby gems from Bundler
      become: no
      bundler: state=present gemfile=~/SourceCode/CategoryCompare-WebApp-Application/Gemfile

    # === Fix Ubuntu's broken Rserve package ===
    # Ubuntu's rserve package doesn't set symlinks properly.
    # See here for more info: https://bugs.launchpad.net/ubuntu/+source/rserve/+bug/1325325
    - file: src=/usr/lib/R/site-library/Rserve/libs/Rserve dest=/usr/lib/R/bin/Rserve owner=root state=link force=yes
    - file: src=/usr/lib/R/site-library/Rserve/libs/Rserve.dbg dest=/usr/lib/R/bin/Rserve.dbg owner=root state=link force=yes

#    - bundler: state=present gemfile=~/SourceCode/CategoryCompare-WebApp-Application/Gemfile